#!/usr/bin/env bash

BINS=(
  pear
  peardev
  pecl
  phar
  phar.phar
  php
  php-cgi
  php-config
  phpdbg
  phpize
)
GLOBAL_BIN="/usr/bin"
HOMEBREW_BIN="/home/linuxbrew/.linuxbrew/bin"

usage() {
  echo "Usage: myphp.sh <command> [version]"
  echo "Commands:"
  echo "  install <version>  - Install PHP version using Homebrew"
  echo "  use <version>      - Switch to a specific PHP version"
  echo "  list              - List installed PHP versions"
  exit 1
}

install_php() {
  local version=$1
  if [ -z "$version" ]; then
    echo "Error: Missing PHP version."
    exit 1
  fi
  if [ "$version" != "php" ]; then
    version="php@$version"
  fi
  echo "Installing PHP $version..."
  brew install "$version"
}

use_php() {
  # User input version that is only major.minor Eg: 8.2
  local mm_version=$1
  local opt=$2
  if [ -z "$mm_version" ]; then
    echo "Error: Missing PHP version."
    exit 1
  fi

  # Extract the exact installed PHP version from brew list output
  local verbose_version
  if [[ "$mm_version" == "latest" ]]; then
    mm_version="php"
  else
    mm_version="php@$mm_version"
  fi

  verbose_version=$(brew list "$mm_version" --versions | awk '{print $2}')
  if [ -z "$verbose_version" ]; then
    echo "Error: Could not determine the exact installed version for PHP $mm_version."
    exit 1
  fi

  local new_php_path="$HOMEBREW_CELLAR/$mm_version/$verbose_version/bin"

  if [ ! -d "$new_php_path" ]; then
    echo "Error: PHP version $mm_version is not installed."
    echo "PHP: $new_php_path"
    exit 1
  fi

  echo "Switching to PHP $mm_version..."
  for bin in "${BINS[@]}"; do
    ln -sf "$new_php_path/$bin" "$HOMEBREW_BIN/$bin"
    if [[ "$opt" == "global" ]]; then
      sudo ln -sf "$new_php_path/$bin" "$GLOBAL_BIN/$bin"
    fi
  done

  echo "PHP is now set to version $mm_version."
}

list_php() {
  local lists
  echo "Installed PHP versions:"
  brew leaves | xargs brew desc --eval-all | grep php
}

if [ $# -lt 1 ]; then
  usage
fi

COMMAND=$1
VERSION=$2
OPT=$3

case "$COMMAND" in
install)
  install_php "$VERSION"
  ;;
use)
  use_php "$VERSION" "$OPT"
  ;;
list)
  list_php
  ;;
*)
  usage
  ;;
esac
